/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    NewSkills: typeof import('./src/components/newSkills.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/Skills.vue')['default']
    StarBackground: typeof import('./src/components/StarBackground.vue')['default']
    TestMenu: typeof import('./src/components/testMenu.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    TypeWrite: typeof import('./src/components/TypeWrite.vue')['default']
    TypeWriter: typeof import('./src/components/TypeWriter.vue')['default']
  }
}
